name: Update Language Servers

on:
    schedule:
        - cron: "0 */6 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-prisma-ls:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Nix
              uses: cachix/install-nix-action@v31

            - name: Install jq and curl
              run: sudo apt-get install -y jq curl

            - name: Run update script
              run: ./servers/prisma-language-server/update.sh

            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: update prisma-language-server"
                  branch: main
    update-gh-action-ls:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Nix
              uses: cachix/install-nix-action@v31

            - name: Install jq and curl
              run: sudo apt-get install -y jq curl

            - name: Run update script
              run: ./servers/gh-action-language-server/update.sh

            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: update gh-action-language-server"
                  branch: main
